version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm config set prefix /usr
      - npm install -g serverless@2.58.0
      - npm install
      - serverless --version

  build:
    commands:
      - npm run build
      - npm install --production
      - serverless deploy # --stage ${ENVIRONMENT}
